[book]
title = "Freenove Manual (Traducción al español)"
authors = ["César San Juan Pastor"]
language = "es"


[output.html]


[output.epub]
# Optional settings
title = "Freenove Manual (Traducción al español)"
author = "César San Juan Pastor"


[output.pdf]
landscape = false
scale = 0.8
paper-width = 8.27
paper-height = 11.7
margin-top = 0.3
margin-bottom = 0.3
margin-left = 0.2
margin-right = 0.2